language: python
sudo: false

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34

install:
  - pip install --upgrade tox
  - "TOX_ENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}"

script:
  - source ~/.venv/bin/activate
  - tox -e $TOX_ENV

notifications:
  email:
    recipients:
      - malex984+travis.cli@gmail.com
  on_success: never
  on_failure: always
