version: '2'
services:
  base:
    image: malex984/dockapp:base
    build: base/
    volumes:
     - /tmp/:/tmp/:rw
     - CFG:/DOCKAPP
     - /etc/localtime:/etc/localtime:ro 
    working_dir: /DOCKAPP
    environment:
     - CFG_DIR=/DOCKAPP
    entrypoint: 
     - /bin/sh

  ddd:
    extends: 
      service: base
    image: malex984/dockapp:ddd
    build: ddd/
    labels:
     - "is_top_app=0"
    volumes:
     - $NO_PROXY:$NO_PROXY
     - $DOCKER_PLUGINS:$DOCKER_PLUGINS
    environment:
     - DOCKER_HOST
     - NO_PROXY
    entrypoint: 
     - /bin/sh

  luncher:
    extends: 
      service: ddd
    entrypoint: 
     - luncher.sh

  omd_agent:
    extends: 
      service: ddd
    image: malex984/dockapp:omd_agent
    build: omd_agent/
    ports:
     - "6556"
     - "8888"
    labels:
     - "is_top_app=0"
    stdin_open: false
    tty: false
    restart: always
    entrypoint: 
     - /sbin/my_init
     - --skip-startup-files
     - --quiet
     - --skip-runit
     - --no-kill-all-on-exit
     - --
    command: 
     - omd_agent_entrypoint.sh

  admin:
    extends: 
      service: ddd
    volumes:
     - /dev:/dev:rw
     - /run/udev:/run/udev
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - /run/systemd:/run/systemd
     - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    privileged: true
    ipc: host
    pid: "host"
    network_mode: "host"
    cap_add:
     - SYS_ADMIN
     - NET_ADMIN
     - ALL

  busybox:
    extends: 
      service: admin
    image: busybox
    entrypoint: 
     - /bin/sh
    
  ptmx:
    extends: 
      service: busybox
    stdin_open: false
    tty: false
    restart: always
    labels:
     - "is_top_app=0"
    command:
     - ptmx/ptmx.sh

  omd:
    extends: 
      service: admin
    image: malex984/dockapp:omd
    build: omd/
    ports:
     - "80"
     - "514"
     - "5667"
     - "5000"     
    labels:
     - "is_top_app=1"
    stdin_open: false
    tty: false
    restart: always
    entrypoint: 
     - /sbin/my_init
     - --skip-startup-files
     - --quiet
     - --skip-runit
     - --no-kill-all-on-exit
     - --
    command: 
     - omd_entrypoint.sh

  pa:
    extends: 
      service: admin
    volumes:
     - ${PULSE_SOCKET}:/run/pulse/native
     - ${PULSE_COOKIE}:/run/pulse_cookie
    environment:
     - PULSE_SERVER=/run/pulse/native
     - PULSE_COOKIE=/run/pulse_cookie
  
  gui:
    extends: 
      service: pa
    environment:
     - QT_X11_NO_MITSHM=1
     - XLIB_SKIP_ARGB_VISUALS=1
     - DISPLAY=unix:0.0
     - XAUTHORITY=/tmp/.docker.xauth
    stdin_open: false
    tty: false
    entrypoint: 
     - /sbin/my_init
     - --skip-startup-files
     - --quiet
     - --skip-runit
     - --no-kill-all-on-exit
     - --


  x11vnc:
    extends: 
      service: gui
    image: malex984/dockapp:x11vnc
    build: x11vnc/
    restart: always
    ports:
     - "127.0.0.1:5900-5910:5900-5910"
    labels:
     - "is_top_app=0"     
    command: 
     - x11vnc.sh


  xeyes:
    extends: 
      service: gui
    image: malex984/dockapp:xeyes
    build: xeyes/
    restart: always    
    labels:
     - "is_top_app=1"
    command: 
     - xeyes
    
  kiosk:
    extends: 
      service: gui
    image: malex984/dockapp:kiosk
    build: kiosk/
    labels:
     - "is_top_app=1"
    entrypoint: 
     - /sbin/my_init 
     - --skip-startup-files
     - --quiet 
     - --skip-runit 
     - --no-kill-all-on-exit 
     - -- 
     - launch.sh
    command: 
     - browser.sh
     - -l
     - http://localhost:5000/default/
    
  kivy:
    extends: 
      service: gui
    image: malex984/dockapp:kivy
    build: kivy/
    labels:
     - "is_top_app=1"
    entrypoint: 
     - /sbin/my_init 
     - --skip-startup-files
     - --quiet 
     - --skip-runit 
     - --no-kill-all-on-exit 
     - -- 
     - launch.sh
    command:
     - /usr/local/src/Deflectouch/run.sh


  dockapp:
    extends: 
      service: gui
    working_dir: /APP/
    volumes:
     - .:/APP
    labels:
     - "is_top_app=1"

  dev_bus_usb:
    extends: 
      service: dockapp
    devices:
     - "/dev/bus/usb:/dev/bus/usb:rwm"
     - "/dev/nvidia0:/dev/nvidia0"
     - "/dev/nvidiactl:/dev/nvidiactl"
     - "/dev/dri:/dev/dri"
     - "/dev/snd:/dev/snd"
     - "/dev/shm:/dev/shm"
     - "/dev/input:/dev/input"


volumes:
  CFG:
    external: true
