version: '2'
services:
  base:
    image: malex984/dockapp:base
    build: base/
    volumes:
     - /tmp/:/tmp/:rw
     - CFG:/DOCKAPP
     - /etc/localtime:/etc/localtime:ro 
    labels:
     - "is_top_app=0"
    working_dir: /DOCKAPP
    environment:
     - CFG_DIR=/DOCKAPP
    entrypoint: 
     - /bin/sh

  ddd:
    extends: 
      service: base
    image: ${DOCKER_COMPOSE_IMAGE}
    build: ddd/
    labels:
     - "is_top_app=0"
    volumes:
     - $NO_PROXY:$NO_PROXY
     - $DOCKER_PLUGINS:$DOCKER_PLUGINS
    environment:
     - DOCKER_HOST
     - NO_PROXY
    entrypoint: 
     - /bin/sh

  luncher:
    extends: 
      service: ddd
    labels:
     - "is_top_app=0"
    entrypoint: 
     - luncher.sh

  admin:
    extends: 
      service: ddd
    volumes:
     - /dev:/dev:rw
     - /run/udev:/run/udev
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - /run/systemd:/run/systemd
     - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    labels:
     - "is_top_app=0"
    privileged: true
    ipc: host
    pid: "host"
    network_mode: "host"
    cap_add:
     - SYS_ADMIN
     - NET_ADMIN
     - ALL
     
  x11:
    extends:
      service: admin
    image: malex984/dockapp:dummy
    build: dummy/
    stdin_open: false
    tty: false
    restart: always
    entrypoint: 
     - /sbin/my_init
     - --skip-startup-files
     - --quiet
     - --skip-runit
     - --no-kill-all-on-exit
     - --
    command: 
     - startXephyr.sh

  xephyr:
    extends:
      service: x11
    environment:
     - XCMD=Xephyr

  xvfb:
    extends:
      service: x11
    environment:
     - XCMD=Xvfb
    command: 
     - startXephyr.sh -screen 0 1024x768x16

  omd_agent:
    extends: 
      service: admin
    image: malex984/dockapp:omd_agent
    build: omd_agent/
    environment:
     - HB_PORT
     - HB_HOST
     - HB_URL
    ports:
     - "6556"
     - "${HB_PORT}"
    stdin_open: false
    tty: false
    restart: always
    labels:
     - "is_top_app=0"
    entrypoint: 
     - /sbin/my_init
     - --skip-startup-files
     - --quiet
     - --skip-runit
     - --no-kill-all-on-exit
     - --
    command: 
     - omd_agent_entrypoint.sh

  hb_test:
    extends: 
      service: admin
    image: malex984/dockapp:omd_agent
    build: omd_agent/
    environment:
     - HB_PORT
     - HB_HOST
     - HB_URL
    ports:
     - "${HB_PORT}"
    stdin_open: false
    tty: false
    restart: always
    labels:
     - "is_top_app=1"
    entrypoint: 
     - /sbin/my_init
     - --skip-startup-files
     - --quiet
     - --skip-runit
     - --no-kill-all-on-exit
     - --
    command: 
     - python2.7 
     - /usr/local/bin/heartbeat2.py 

  busybox:
    extends: 
      service: admin
    labels:
     - "is_top_app=0"
    image: busybox
    entrypoint: 
     - /bin/sh
    
  ptmx:
    extends: 
      service: busybox
    stdin_open: false
    tty: false
    restart: always
    command:
     - ptmx/ptmx.sh

  reboot:
    extends: 
      service: busybox
    stdin_open: false
    tty: false
    command:
     - reboot

  omd:
    extends: 
      service: admin
    image: malex984/dockapp:omd
    build: omd/
    ports:
     - "80"
     - "514"
     - "5667"
     - "5000"     
    labels:
     - "is_top_app=1"
    stdin_open: false
    tty: false
    restart: always
    volumes:
     - OMD:/omd/sites
    entrypoint: 
     - /sbin/my_init
     - --skip-startup-files
     - --quiet
     - --skip-runit
     - --no-kill-all-on-exit
     - --
    command: 
     - omd_entrypoint.sh

  pa:
    extends: 
      service: admin
    labels:
     - "is_top_app=0"
    volumes:
     - ${PULSE_SOCKET}:/run/pulse/native
     - ${PULSE_COOKIE}:/run/pulse/cookie
    environment:
     - PULSE_SERVER=/run/pulse/native
     - PULSE_COOKIE=/run/pulse/cookie
  
  gui:
    extends: 
      service: pa
    labels:
     - "is_top_app=0"
    environment:
     - QT_X11_NO_MITSHM=1
     - XLIB_SKIP_ARGB_VISUALS=1
     - XAUTHORITY
     - DISPLAY
    stdin_open: false
    tty: false
    entrypoint: 
     - /sbin/my_init
     - --skip-startup-files
     - --quiet
     - --skip-runit
     - --no-kill-all-on-exit
     - --

  qrhandler:
    extends: 
      service: gui
    labels:
     - "is_top_app=0"
    image: malex984/dockapp:qrhandler
    build: qrhandler/
    restart: always
    volumes:
     - supernova:/supernova
    environment:
     - qrs_screenshot_message="Bild gespeichert.\n\nImage saved."
     - qr_uploadlocs="/supernova"
     - QR_DEVICE_ID="AT Translated Set 2 keyboard"
    command: 
     - qrhandler.sh
 
  x11vnc:
    extends: 
      service: gui
    labels:
     - "is_top_app=0"
    image: malex984/dockapp:x11vnc
    build: x11vnc/
    restart: always
    ports:
     - "127.0.0.1:5900-5910:5900-5910"
    command: 
     - x11vnc.sh


  xeyes:
    extends: 
      service: gui
    image: malex984/dockapp:xeyes
    build: xeyes/
    restart: always    
    labels:
     - "is_top_app=1"
    command: 
     - xeyes
    
  kiosk:
    extends: 
      service: gui
    image: malex984/dockapp:kiosk
    build: kiosk/
    labels:
     - "is_top_app=1"
    entrypoint: 
     - /sbin/my_init 
     - --skip-startup-files
     - --quiet 
     - --skip-runit 
     - --no-kill-all-on-exit 
     - -- 
     - launch.sh
    command: 
     - browser.sh
     
  chrome:
    extends: 
      service: gui
    image: malex984/dockapp:chrome
    build: chrome/
    labels:
     - "is_top_app=1"
    entrypoint: 
     - /sbin/my_init 
     - --skip-startup-files
     - --quiet 
     - --skip-runit 
     - --no-kill-all-on-exit 
     - -- 
     - launch.sh
    command: 
     - browser.sh
     - http://localhost:5000/default/

  opera:
    extends: 
      service: chrome
    environment:
     - GOOGLE_CHROME=opera

  chromium:
    extends: 
      service: chrome
    environment:
     - GOOGLE_CHROME=chromium-browser

  kivy:
    extends: 
      service: gui
    image: malex984/dockapp:kivy
    build: kivy/
    labels:
     - "is_top_app=1"
    entrypoint: 
     - /sbin/my_init 
     - --skip-startup-files
     - --quiet 
     - --skip-runit 
     - --no-kill-all-on-exit 
     - -- 
     - launch.sh
    command:
     - /usr/local/src/Deflectouch/run.sh


  dockapp:
    extends: 
      service: gui
    volumes:
     - .:/DOCKAPP
    working_dir: /DOCKAPP/
    labels:
     - "is_top_app=1"

  register:
    extends: 
      service: dockapp
    image: imaginary.mfo.de:5000/malex984/alpine
    devices:
     - "/dev/bus/usb:/dev/bus/usb:rwm"
     - "/dev/nvidia0:/dev/nvidia0"
     - "/dev/nvidiactl:/dev/nvidiactl"
     - "/dev/dri:/dev/dri"
     - "/dev/snd:/dev/snd"
     - "/dev/shm:/dev/shm"
     - "/dev/input:/dev/input"

volumes:
  CFG:
    external: true
  OMD:
    external: true
  supernova:
    driver: local
