version: '2.1'
services:
  kiosk_browser_index:
    extends: 
      file: docker-compose.yml
      service: kiosk_base
    command:
     - browser.sh
     - -vvvim
     ### Zoom factor: 1.0 => 100%
     #- -z
     #- "1.0"
     ### show developer tools: "-d"
     #- -d
#     - "${HILBERT_WEBGL_APPS:-https://supernova.eso.org/exhibition/register/}"
    environment:
     - "APP_ID=${HILBERT_APPLICATION_ID:-kiosk_browser_index}"
